/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package armazemclientes.core.views;


import armazemclientes.core.controlador.VendaControlador;
import armazemclientes.core.entidade.VendaEntidade;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author CLIENTE
 */
public class InterfaceDireta extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceDireta
     */
    public InterfaceDireta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioDinheiro = new javax.swing.JRadioButton();
        radioPix = new javax.swing.JRadioButton();
        radioCC = new javax.swing.JRadioButton();
        radioCD = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        botaoListar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("REGISTRAR COMPRA");

        inputVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVendaActionPerformed(evt);
            }
        });

        jLabel4.setText("Venda:");

        radioDinheiro.setText("DINHEIRO");
        radioDinheiro.setOpaque(true);
        radioDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinheiroActionPerformed(evt);
            }
        });

        radioPix.setText("PIX");
        radioPix.setOpaque(true);
        radioPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPixActionPerformed(evt);
            }
        });

        radioCC.setText("CC");
        radioCC.setOpaque(true);
        radioCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCCActionPerformed(evt);
            }
        });

        radioCD.setText("CD");
        radioCD.setOpaque(true);
        radioCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCDActionPerformed(evt);
            }
        });

        jLabel5.setText("FormaPag.");

        botaoListar.setBackground(new java.awt.Color(204, 255, 204));
        botaoListar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botaoListar.setText("Buscar");
        botaoListar.setToolTipText("");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(102, 255, 102));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botaoCadastrar.setText("Salvar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        jMenu1.setText("RETORNAR");
        jMenu1.setFont(new java.awt.Font("Perpetua", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Perpetua", 1, 12)); // NOI18N
        jMenuItem1.setText("CADASTRO DO CLIENTE");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(radioDinheiro)
                                .addGap(18, 18, 18)
                                .addComponent(radioPix)
                                .addGap(27, 27, 27)
                                .addComponent(radioCC)
                                .addGap(31, 31, 31)
                                .addComponent(radioCD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(botaoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioDinheiro)
                    .addComponent(radioPix)
                    .addComponent(radioCC)
                    .addComponent(radioCD))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVendaActionPerformed

    private void radioDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinheiroActionPerformed
        ButtonGroup bg = new ButtonGroup();
        bg.add(radioDinheiro);
        bg.add(radioPix);
        bg.add(radioCC);
        bg.add(radioCD);
    }//GEN-LAST:event_radioDinheiroActionPerformed

    private void radioPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPixActionPerformed
        ButtonGroup bg02 = new ButtonGroup();
        bg02.add(radioPix);
        bg02.add(radioDinheiro);
        bg02.add(radioCC);
        bg02.add(radioCD);
        
    }//GEN-LAST:event_radioPixActionPerformed

    private void radioCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCCActionPerformed
        ButtonGroup bg03 = new ButtonGroup();
        bg03.add(radioCC);
        bg03.add(radioCD);
        bg03.add(radioPix);
        bg03.add(radioDinheiro);
    }//GEN-LAST:event_radioCCActionPerformed

    private void radioCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCDActionPerformed
        ButtonGroup bg04 = new ButtonGroup();
        bg04.add(radioCD);
        bg04.add(radioDinheiro);
        bg04.add(radioPix);
        bg04.add(radioCC);
    }//GEN-LAST:event_radioCDActionPerformed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        ListaDasVendas listaV = new ListaDasVendas();
        listaV.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed

        if(inputVenda.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Cadastro incompleto!");
        }
        else{
            VendaEntidade venda = new VendaEntidade();
            venda.setValorVenda(Double.parseDouble(inputVenda.getText()));

            if(radioDinheiro.isSelected()){
                venda.setFp(radioDinheiro.getText());
            }
            if(radioPix.isSelected()){
                venda.setFp(radioPix.getText());
            }
            if(radioCC.isSelected()){
                venda.setFp(radioCC.getText());
            }
            if(radioCD.isSelected()){
                venda.setFp(radioCD.getText());
            }
            if(radioDinheiro.isSelected() || radioPix.isSelected() || radioCC.isSelected() || radioCD.isSelected()){
                VendaControlador vendaControlador = new VendaControlador();
                JOptionPane.showMessageDialog(this, vendaControlador.salvarVenda(venda));
                return;
            }
            if(!radioDinheiro.isSelected() || !radioPix.isSelected() || !radioCC.isSelected() || !radioCD.isSelected()){
                JOptionPane.showMessageDialog(this, "Escolha a forma de pagamento!");
            }
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Interface inter = new Interface();
        inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDireta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoListar;
    private javax.swing.JTextField inputVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton radioCC;
    private javax.swing.JRadioButton radioCD;
    private javax.swing.JRadioButton radioDinheiro;
    private javax.swing.JRadioButton radioPix;
    // End of variables declaration//GEN-END:variables
}
